### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by paddingme** [paddingme/convert-issues-to-markdown-files#1]
- [ ] issues 100 的限制
- [ ] 如果没有 ./md 文件夹 应该自行创建
- [ ] 增量发布
- [ ] 实现可配置
- [ ]  单元测试：
  - [ ]  没有 username
  - [ ]  没有 repos 或者  repos 不为数组
  - [ ]  github 没有该 username
  - [ ]  该用户没有 该 repos
  - [ ]  该用户该 repos 没有该  label?
- [ ]  写 redame
- [ ] 写篇 blog 介绍下
- [ ] 发布到 npm
